services:
  web:
    build: ./app
    ports:
      - "8087:8087"
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user:password@db:5432/clickdb
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=clickdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 